### ISSUE TITLE
[Madrob] update template sheet

### ISSUE THREAD

**Issue by aremazeilles** [madrob-beast/madrob_beast_pi#20]
As Madrob is complete on the software side, looking at the excel sheet. 
I think PI description is ok.

The PI Algo could be simplified:

```yaml
name: run_madrob
url_paper: none
url_code: https://github.com/madrob-beast/madrob_beast_pi
docker_image: pi_madrob_beast (Alfonso would you need here the complete url?)
associated PI: [all_mentioned; above]
input files: [events.csv, wrench.csv, jointState.csv, testbed_config.yaml]
input command: [run_madrob, events.csv, wrench.csv, jointState.csc, testbed_config.yaml]
```

Would you agree?
@alfonsoTecnalia, do you need the output folder to be listed within the input command as well?
